CREATE DATABASE IF NOT EXISTS construction_company 
    CHARACTER SET utf8mb4 
    COLLATE utf8mb4_unicode_ci;


CREATE TABLE IF NOT EXISTS construction_company.users(
	id INT AUTO_INCREMENT NOT NULL,
	first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(63) NOT NULL UNIQUE,
    `password` VARCHAR(100) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    `role` ENUM('SYS_ADMIN', 'RESOURCE_MANAGER', 'CONSTRUCTION_SUPERVISOR', 'WAREHOUSE_SUPERVISOR', 'CEO') NOT NULL,
    PRIMARY KEY(id)
);